### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by ozanmutlu** [emrementese/binance-ema#4]
Hello @emrementese,

Thanks for the package first of all, really good contribution to community. When I try to install the package I got an encoding error, as a solution it would be a good idea to add "encoding='UTF-8'" in setup.py;

with open("README.md", "r", encoding='UTF-8') as readme_file:
    readme = readme_file.read()

**Comment by emrementese** [comment]
Dear Ozan,

	Thanks for feedback. I will examine to your code.

> ozanmutlu ***@***.***> şunları yazdı (3 Nis 2022 13:39):
> 
>

**Comment by emrementese** [comment]
I add to 'UTF-8' options for encoding. Thanks for feedback @ozanmutlu
